[[protocols]]
name = "nec_orangepiplus2e"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x877c0c = "KEY_1"
0x877c0d = "KEY_2"
0x877c0e = "KEY_3"
0x877c0f = "KEY_4"
0x877c10 = "KEY_5"
0x877c11 = "KEY_6"
0x877c12 = "KEY_7"
0x877c13 = "KEY_8"
0x877c15 = "KEY_9"
0x877c16 = "KEY_0"
0x877c02 = "KEY_STOP"
0x877c4a = "KEY_PAUSE"
0x877c01 = "KEY_PLAY"
0x877c06 = "KEY_NEXT"
0x877c05 = "KEY_PREVIOUS"
0x877cd4 = "KEY_RIGHT"
0x877cd3 = "KEY_LEFT"
0x877cd2 = "KEY_UP"
0x877cd1 = "KEY_DOWN"
0x877c25 = "KEY_POWER"
0x877cc8 = "KEY_POWER2"
0x877c85 = "KEY_CD"
0x877c07 = "KEY_CHANNELUP"
0x877c04 = "KEY_CHANNELDOWN"
